POST http://localhost:3000/api/patients
Content-Type: application/json

{
  "name": "John Doe",
  "dateOfBirth": "1990-01-01",
  "ssn": "010190-123X",
  "gender": "male",
  "occupation": "Leet Cop"
}
